
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pickle Developement CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        id: jdk8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Push PicklePartyBlock.jar
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://infra-dev.picklemc.fr/registry/partyblock?eventStream=false'
          files: '{ "data": "${{ github.workspace }}/build/libs/PicklePartyBlock-all.jar" }'
